# Server
server.port=8080

# JWT
app.jwt.secret=ThisIsATestSecretKeyForJWTAuthentication123456789
app.jwt.expiration=86400000

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/outpass_management
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect